### ISSUE TITLE
А почему у нас последняя выложенная на npm версия – 1.1.0 ?

### ISSUE THREAD

**Issue by eGavr** [gemini-testing/gemini-faildump#8]
cc @j0tunn @sipayRT @tormozz48

**Comment by j0tunn** [comment]
У андрюхи надо спросить, он ее выкатывал

**Comment by sipayRT** [comment]
![](http://cs418528.vk.me/v418528002/7386/VMQQIQP8j4s.jpg)

**Comment by Kreozot** [comment]
Что-нибудь поменялось за пару лет? )

**Comment by j0tunn** [comment]
Да, последняя версия сейчас - 6.0.0
